### ISSUE TITLE
Performance maximum elements

### ISSUE THREAD

**Issue by Sebastix** [srobbin/jquery-approach#5]
Hi,

What's the maximum of elements without losing performance?

Gr Sebastian

**Comment by srobbin** [comment]
Hi,

I'm not really sure. I imagine that's a moving target, since it's dependent on a bunch of different things: browser, computer speed, what other scripts are on the page, etc.

That said, I'd think you would want to keep the number relatively low. This isn't a very efficient plugin.

Cheers,
Scott

**Comment by Sebastix** [comment]
Thanks for your quick answer!

Your demo with 40 images is performing good, I tried it with 150 smaller images but with my Macbook Pro in Chrome it wasn't a success. So keeping the number of element low is a must =)
